[build]
builder = "nixpacks"
buildCommand = "npm install --production=false && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
healthcheckInterval = 30

[deploy.envs]
NODE_ENV = "production" 