[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 500
restartPolicyType = "on_failure"
healthcheckInterval = 45
healthcheckMaxRetries = 5

[deploy.envs]
NODE_ENV = "production"
PORT = "8080" 